version: "3.5"
services:


  # ros
  ros-is:
    image: ros-is:latest
    hostname: ros-is
    container_name: ros-is
    volumes:
      - ./config/config.yaml:/root/is-workspace/config/config.yaml
    
    network_mode: host
    environment:
      - ROS_MASTER_URI=http://172.18.1.1:11311/
      - ROS_IP=172.18.1.20
    command: ["/bin/bash", "-c", "source /opt/ros/melodic/setup.bash && source /root/catkin_ws/devel/setup.bash && source /root/is-workspace/install/setup.bash && /root/is-workspace/install/is-core/install/integration-service /root/is-workspace/config/config.yaml"]

networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24

