types:
    idls:
        - >
            struct HelloWorld {
                string data;
            };

            struct TurtlePosition {
                float x;
                float y;
                float theta;
                float linear_velocity;
                float angular_velocity;
            };
            
            struct ThermalInfo {
                float temperatureMax;
                float temperatureMin;
                sequence<double> positionMax;
                sequence<double> positionMin;
            };
systems:
    ros1: { type: ros1 }
    fiware: { type: fiware, host: "161.72.18.76", port: 1026, types-from: ros1 }

routes:
    ros1_to_fiware: { from: ros1, to: fiware }

topics:
    GARA.IRCamera.thermal.info: { type: "gara_messages/IRCameraTemperatureInfo", route: ros1_to_fiware, remap: {fiware: {type: ThermalInfo}, ros1: { topic: "thermal/temperature_info" } } }
